In [1]:
import os
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
user_name = os.environ.get("root")
password =os.environ.get("Defne1469")

In [13]:
connection = mysql.connector.connect(host="127.0.0.1",
                                   user  = "root" ,
                                     passwd="",
                                   db="northwind",
                                     auth_plugin='mysql_native_password')

In [14]:
connection

In [15]:
tables=pd.read_sql_query("SHOW TABLES FROM northwind",connection)

In [16]:
tables["Tables_in_northwind"]

0                       customers
1             employee_privileges
2                       employees
3     inventory_transaction_types
4          inventory_transactions
5                        invoices
6                   order_details
7            order_details_status
8                          orders
9                   orders_status
10              orders_tax_status
11                     privileges
12                       products
13         purchase_order_details
14          purchase_order_status
15                purchase_orders
16                  sales_reports
17                       shippers
18                        strings
19                      suppliers
Name: Tables_in_northwind, dtype: object

In [17]:
customers = pd.read_sql_query(f"Select * from customers",connection)
employee_privileges = pd.read_sql_query(f"Select * from employee_privileges",connection)
employees = pd.read_sql_query(f"Select * from employees",connection)
inventory_transaction_types = pd.read_sql_query(f"Select * from inventory_transaction_types",connection)
inventory_transactions = pd.read_sql_query(f"Select * from inventory_transactions",connection)
invoices = pd.read_sql_query(f"Select * from invoices",connection)
order_details = pd.read_sql_query(f"Select * from order_details",connection)
order_details_status = pd.read_sql_query(f"Select * from order_details_status",connection)
orders = pd.read_sql_query(f"Select * from orders",connection)
orders_status = pd.read_sql_query(f"Select * from orders_status",connection)
orders_tax_status = pd.read_sql_query(f"Select * from orders_tax_status",connection)
privileges = pd.read_sql_query(f"Select * from privileges",connection)
products = pd.read_sql_query(f"Select * from products",connection)
purchase_order_details = pd.read_sql_query(f"Select * from purchase_order_details",connection)
purchase_order_status = pd.read_sql_query(f"Select * from purchase_order_status",connection)
purchase_orders = pd.read_sql_query(f"Select * from purchase_orders",connection)
sales_reports = pd.read_sql_query(f"Select * from sales_reports",connection)
shippers= pd.read_sql_query(f"Select * from shippers",connection)
strings = pd.read_sql_query(f"Select * from strings",connection)
suppliers = pd.read_sql_query(f"Select * from suppliers",connection)

In [9]:
customers

,id,company,last_name,first_name,email_address,job_title,business_phone,home_phone,mobile_phone,fax_number,address,city,state_province,zip_postal_code,country_region,web_page,notes,attachments
0,1,Company A,Bedecs,Anna,None,Owner,(123)555-0100,None,None,(123)555-0101,123 1st Street,Seattle,WA,99999,USA,None,None,b''
1,2,Company B,Gratacos Solsona,Antonio,None,Owner,(123)555-0100,None,None,(123)555-0101,123 2nd Street,Boston,MA,99999,USA,None,None,b''
2,3,Company C,Axen,Thomas,None,Purchasing Representative,(123)555-0100,None,None,(123)555-0101,123 3rd Street,Los Angelas,CA,99999,USA,None,None,b''
3,4,Company D,Lee,Christina,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,123 4th Street,New York,NY,99999,USA,None,None,b''
4,5,Company E,O’Donnell,Martin,None,Owner,(123)555-0100,None,None,(123)555-0101,123 5th Street,Minneapolis,MN,99999,USA,None,None,b''
5,6,Company F,Pérez-Olaeta,Francisco,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,123 6th Street,Milwaukee,WI,99999,USA,None,None,b''
6,7,Company G,Xie,Ming-Yang,None,Owner,(123)555-0100,None,None,(123)555-0101,123 7th Street,Boise,ID,99999,USA,None,None,b''
7,8,Company H,Andersen,Elizabeth,None,Purchasing Representative,(123)555-0100,None,None,(123)555-0101,123 8th Street,Portland,OR,99999,USA,None,None,b''
8,9,Company I,Mortensen,Sven,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,123 9th Street,Salt Lake City,UT,99999,USA,None,None,b''
9,10,Company J,Wacker,Roland,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,123 10th Street,Chicago,IL,99999,USA,None,None,b''
10,11,Company K,Krschne,Peter,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,123 11th Street,Miami,FL,99999,USA,None,None,b''
11,12,Company L,Edwards,John,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,123 12th Street,Las Vegas,NV,99999,USA,None,None,b''
12,13,Company M,Ludick,Andre,None,Purchasing Representative,(123)555-0100,None,None,(123)555-0101,456 13th Street,Memphis,TN,99999,USA,None,None,b''
13,14,Company N,Grilo,Carlos,None,Purchasing Representative,(123)555-0100,None,None,(123)555-0101,456 14th Street,Denver,CO,99999,USA,None,None,b''
14,15,Company O,Kupkova,Helena,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,456 15th Street,Honolulu,HI,99999,USA,None,None,b''
15,16,Company P,Goldschmidt,Daniel,None,Purchasing Representative,(123)555-0100,None,None,(123)555-0101,456 16th Street,San Francisco,CA,99999,USA,None,None,b''
16,17,Company Q,Bagel,Jean Philippe,None,Owner,(123)555-0100,None,None,(123)555-0101,456 17th Street,Seattle,WA,99999,USA,None,None,b''
17,18,Company R,Autier Miconi,Catherine,None,Purchasing Representative,(123)555-0100,None,None,(123)555-0101,456 18th Street,Boston,MA,99999,USA,None,None,b''
18,19,Company S,Eggerer,Alexander,None,Accounting Assistant,(123)555-0100,None,None,(123)555-0101,789 19th Street,Los Angelas,CA,99999,USA,None,None,b''
19,20,Company T,Li,George,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,789 20th Street,New York,NY,99999,USA,None,None,b''
20,21,Company U,Tham,Bernard,None,Accounting Manager,(123)555-0100,None,None,(123)555-0101,789 21th Street,Minneapolis,MN,99999,USA,None,None,b''
21,22,Company V,Ramos,Luciana,None,Purchasing Assistant,(123)555-0100,None,None,(123)555-0101,789 22th Street,Milwaukee,WI,99999,USA,None,None,b''
22,23,Company W,Entin,Michael,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,789 23th Street,Portland,OR,99999,USA,None,None,b''
23,24,Company X,Hasselberg,Jonas,None,Owner,(123)555-0100,None,None,(123)555-0101,789 24th Street,Salt Lake City,UT,99999,USA,None,None,b''
24,25,Company Y,Rodman,John,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,789 25th Street,Chicago,IL,99999,USA,None,None,b''
25,26,Company Z,Liu,Run,None,Accounting Assistant,(123)555-0100,None,None,(123)555-0101,789 26th Street,Miami,FL,99999,USA,None,None,b''
26,27,Company AA,Toh,Karen,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,789 27th Street,Las Vegas,NV,99999,USA,None,None,b''
27,28,Company BB,Raghav,Amritansh,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,789 28th Street,Memphis,TN,99999,USA,None,None,b''
28,29,Company CC,Lee,Soo Jung,None,Purchasing Manager,(123)555-0100,None,None,(123)555-0101,789 29th Street,Denver,CO,99999,USA,None,None,b''

NameError: name 'output' is not defined

'suppliers'